<a href="https://colab.research.google.com/github/yrasool/GitHubWorkshop/blob/main/Linear_Algebra_Ankur_mali-lectures_practice_for_me_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
x = (1,2,3,4,)
y = (5,6,7,8)
n =len(x)
if n == len(y):
  result = 0
  for i in range (n):
    result += x[i] *y[i]
    print(result)

#It is clear that in the code above we could change line 7 to result += y[i] * x[i] without affecting the result.
#We can use the numpy module to apply the same operation, to calculate the inner product. We import the numpy module and assign it a name np for the following code:

In [6]:
import numpy as np

x = np.array([1,2,3,4])
y = np.array([5,6,7,8])

print("x:", x)
print("y:", y)

np.dot(y,x)#dot product of the two vectors

#Both x and y are row vectors we can transform them to column vectors
x.shape = (4,1)
print("xT :" , x)
y.shape =(4,1)
print("yT:", y)

x: [1 2 3 4]
y: [5 6 7 8]
xT : [[1]
 [2]
 [3]
 [4]]
yT: [[5]
 [6]
 [7]
 [8]]


In [10]:
x = np.array([1,2,3,4])
y = np.array([5,6,7,8])
print("y:", y.T)
print("x:", x.T)


#ONLY IF WE DECLARE VARIABLES TO BE MATRIX INSTEAD OF ARRAUY WILL THE TRANSPOSE WORK
x = np.array([[1,2,3,4]])
y = np.array([[5,6,7,8]])
print("y:", y.T)
print("x:", x.T)

np.dot(y,x.T)
#to get array as 70 
np.dot(y,x.T)[0][0]





y: [5 6 7 8]
x: [1 2 3 4]
y: [[5]
 [6]
 [7]
 [8]]
x: [[1]
 [2]
 [3]
 [4]]


70

In [13]:
import tensorflow as tf
tf.reduce_sum(tf.multiply(x,y), 1)
tf.reduce_sum(tf.multiply(y,x), 1)
tf.shape(x)
tf.shape(y)
print(y.T)

[[5]
 [6]
 [7]
 [8]]


In [15]:
x = np.array([[1,2,3,4]])
print("x:", x)
print("xT : ", np.reshape(x, (4,1)))
print("xT : ",x.T)
print("xT : ",x.transpose())


x: [[1 2 3 4]]
xT :  [[1]
 [2]
 [3]
 [4]]
xT :  [[1]
 [2]
 [3]
 [4]]
xT :  [[1]
 [2]
 [3]
 [4]]


In [18]:
#WE can use outer product

x = np.array([[1,2,3,4]])
y = np.array([[5,6,7,8]])

x.T *y
np.outer(x,y)




<tf.Tensor: shape=(1, 4, 1, 4), dtype=int64, numpy=
array([[[[ 5,  6,  7,  8]],

        [[10, 12, 14, 16]],

        [[15, 18, 21, 24]],

        [[20, 24, 28, 32]]]])>

In [22]:
#using arrays no instead of matrices
x = np.array([1,2,3,4])
y = np.array([5,6,7,8])


np.outer(x,y)
tf.tensordot(x,y,axes = 0)



<tf.Tensor: shape=(4, 4), dtype=int64, numpy=
array([[ 5,  6,  7,  8],
       [10, 12, 14, 16],
       [15, 18, 21, 24],
       [20, 24, 28, 32]])>

In [26]:
#Matrix Vector Product
#Variable in TensorFlow, you need to specify its initial value. This can be a scalar value, a list, an array, or a tensor. Once a Variable is created, you can perform various operations on it, such as adding, multiplying, or reshaping it.
#In summary, Variable is a special kind of tensor that is used to store mutable state in TensorFlow. 
import numpy as np
A = np.array([[4,5,6],
              [7,8,6]])
A*2


A_t = tf.Variable([[4,5,6],
                   [7,8,9]])
tf.multiply(A_t,2)  

A = np.array([[4,5,6],
              [7,8,6]])
x = np.array([1,2,3])
A.dot(x)

A = tf.Variable([[4,5,6],
                   [7,8,9]])
x = tf.Variable([1,2,3])  
tf.reduce_sum(tf.multiply(A,x), 1)





<tf.Tensor: shape=(2,), dtype=int32, numpy=array([32, 50], dtype=int32)>

In [29]:
#Matrix Multiplication
import numpy as np
A = np.array([[0,1,2],
              [3,4,5],
              [6,7,8],
              [9,10,11]])
print("A:", A)
A.shape

A= tf.Variable([[0,1,2],
              [3,4,5],
              [6,7,8],
              [9,10,11]])
print(A)

#The shape property of a matrix contains the 
 #(number of rows) and (number of columns) properties in a tuple, 
 #in that particular order. We can create an identity matrix for the use in 
 #by using the n value:




A: [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
<tf.Variable 'Variable:0' shape=(4, 3) dtype=int32, numpy=
array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]], dtype=int32)>


array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [ ]:
#Identity Matrix, the 
np.identity(A.shape[1],dtype = "int")#this gives us identity matrix of
#shape 3*3
tf.eye(3,3)#tensor flow identity matrix
#To generate an identity matrix for the use in 
#we would use the m value:
#We can compute the dot product of  and its identity matrix :
np.identity(A.shape[0], dtype="int")
n = A.shape[1]
I = np.array(np.identity(n,dtype ="int"))
np.dot(A,I)
#using tensorflow
#By specifying axes=1 in tf.tensordot(A, I, axes=1), you are telling TensorFlow to contract the second axis of A with the first axis of I. This means that the second 
#dimension of A (which has size 3) will be multiplied element-wise with the first dimension of I (which also has size 3).
#The resulting tensor will have the shape of the remaining axes after the contraction. In this case, the resulting tensor will be a 4x3 tensor with the same 
#values as A since each element in A will be multiplied by the corresponding element in I.
#Thus, the resulting tensor will have the same shape as A since each element in A is multiplied by the corresponding element in I
I= tf.eye(3,3,dtype = tf.dtypes.int32)
tf.tensordot(A,I,axes = 1)
#using m instead of n 
m = A.shape[1]
I = np.array(np.identity(m, dtype = "int"))
np.dot(A,I) 
#The use of m and n is interchangeable in this case, as they 
#both represent the number of columns in A. In the NumPy example, n is used to calculate the size of the identity matrix I, while in the TensorFlow example the size of I is explicitly set to 3. In both cas
#shape as A, since the number of columns in A matches the number 
#of rows in I.


In [30]:
#Diagonal Matrix

#D = diag(d1,d2,d3,dn)
#use diag function in numpy
import numpy as np
A = np.array([[0,1,2,3],
              [4,5,6,7],
              [8,9,10,11],
              [12,13,14,15]])
np.diag(A)

np.diag(A, k =1 )#n np.diag(A, k=1), you are extracting the elements one diagonal 
#above the main diagonal of the matrix A. This results in a 1-D array containing 
#the values [1, 6, 11], which are the elements A[0,1], A[1,2], and A[2,3].

array([ 1,  6, 11])

In [ ]:
tf.linalg.diag_part(A)
tf.linalg.diag_part(A, k =1 )
